### ISSUE TITLE
Very low AP when using cfg.data.val to build the dataset

### ISSUE THREAD

**Issue by Jossome** [shinya7y/UniverseNet#10]
Hi, I'm currently trying universenet on Waymo dataset. I used your WaymoCOCO code to generate f0 training and validation set.

After training, I run `tools/test.py` with the default setting. It loads 4038 samples for validation, and the performance is good. However, when I change [this line](https://github.com/shinya7y/UniverseNet/blob/master/tools/test.py#L153) to `dataset = build_dataset(cfg.data.val)`, the progress bar shows only 3945 samples, and the resulting AP is very very low (close to 0). 

I checked the [config file](https://github.com/shinya7y/UniverseNet/blob/master/configs/_base_/datasets/waymo_open_2d_detection_f0_mstrain_640_1280.py) - the cfg.data.val has exactly the same field as cfg.data.test. 

What was going wrong in this case?

**Comment by shinya7y** [comment]
Is `test_mode` set to True by replacing other `cfg.data.test` in [test.py](https://github.com/shinya7y/UniverseNet/blob/master/tools/test.py)?

**Comment by shinya7y** [comment]
For changing test data, it's better to edit configs or use `--cfg-options`.
Example for COCO test: `--cfg-options "data.test.ann_file=data/coco/annotations/image_info_test-dev2017.json" "data.test.img_prefix=data/coco/test2017/"`

**Comment by Jossome** [comment]
> Is `test_mode` set to True by replacing other `cfg.data.test` in [test.py](https://github.com/shinya7y/UniverseNet/blob/master/tools/test.py)?

Yes this solves my problem. When I change it to `cfg.data.val`, I also need to set `cfg.data.val.test_mode=True`, as in [here in test.py](https://github.com/shinya7y/UniverseNet/blob/master/tools/test.py#L134-L139).

Thanks!

**Comment by Jossome** [comment]
@shinya7y Hi, I have a small question about training on waymo, so i'm just putting it in this thread - 
For the models on waymo datasets provided [here](https://github.com/shinya7y/UniverseNet/tree/master/configs/waymo_open), did you train them with images of all 5 cameras or just the front camera?

**Comment by shinya7y** [comment]
I trained them with images of all 5 cameras.
