### ISSUE TITLE
Group error

### ISSUE THREAD

**Issue by CuongNN218** [shinya7y/UniverseNet#15]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
when I trained with 1 gpu, this process interrupted with the following issue:
![image](https://user-images.githubusercontent.com/26113323/110064831-79678980-7da0-11eb-91bb-b9c35a52ae17.png)

**Reproduction**
1. What command or script did you run?
```
python3 tools/train.py configs/xray/universalnet_50_xray.py

```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
 I just use universalnet_r50 with change the number of classes and change sample per gpu to 4.
3. What dataset did you use?
I just use my custom dataset inherited from coco dataset with 14 class. 
**Environment**
follow your requirements

**Comment by shinya7y** [comment]
Duplicated https://github.com/shinya7y/UniverseNet/issues/8
Please use tools/dist_train.sh and tools/dist_test.sh, or modify SyncBN to BN manually.
