### ISSUE TITLE
Any technical reports?

### ISSUE THREAD

**Issue by lucasjinreal** [shinya7y/UniverseNet#2]
Model architecture design and speed comparsion with other models?

**Comment by shinya7y** [comment]
No technical report for now.

Model architecture:
Overall architectures are as shown in the files in [configs/_base_/models](https://github.com/shinya7y/UniverseNet/tree/master/configs/_base_/models).
For the architecture of each part, please see the papers of ATSS, SEPC, Res2Net, DCN, and GFL, especially Figure 5 in [the SEPC paper](https://openaccess.thecvf.com/content_CVPR_2020/papers/Wang_Scale-Equalizing_Pyramid_Convolution_for_Object_Detection_CVPR_2020_paper.pdf).

Speed comparison:
Please see [fps on COCO](https://github.com/shinya7y/UniverseNet/tree/master/configs/universenet) and [fps on Waymo Open](https://github.com/shinya7y/UniverseNet/tree/master/configs/waymo_open).
The results of other methods in [the speed/accuracy trade-offs graph](https://github.com/shinya7y/UniverseNet/blob/master/docs/imgs/coco_ap_time_epoch.png) are based on papers or github.

**Comment by shinya7y** [comment]
https://arxiv.org/abs/2103.14027
I submitted a paper to arXiv. Thank you for waiting.

![coco_ap_time_epoch](https://user-images.githubusercontent.com/42844407/112571346-317dd480-8e2b-11eb-8b1e-a97ba2e97997.png)
