### ISSUE TITLE
There are many memory occupation in GPU0 

### ISSUE THREAD

**Issue by John-Yao** [shinya7y/UniverseNet#23]
Hi,

I trained  detector in my dataset using 'universenet50_gfl_xxx.py' and there were many memory occupation in GPU0 
![image](https://user-images.githubusercontent.com/22048231/124895505-2f710780-e00f-11eb-9778-5ffb17f407aa.png)

And I noticed that extra memory occupation occured when the program go to the lines:

`
            model = MMDistributedDataParallel(
            model.cuda(),
            device_ids=[torch.cuda.current_device()],
            broadcast_buffers=False,
            find_unused_parameters=find_unused_parameters)
`

Also I try to train detector  with cascade rcnn. There are no memory occupation

Could you provide some suggestion?

Thanks!

**Comment by shinya7y** [comment]
Thank you for pointing out the issue.
ImageNet pretrained Res2Net seems to be loaded on GPU0. Related issue: https://github.com/open-mmlab/mmdetection/issues/3646

Please change configs as below:
```python
    pretrained=('https://github.com/shinya7y/weights/releases/download/v1.0.2/'
                'res2net50_v1b_26w_4s-3cf99910_mmdetv2-92ed3313.pth'),
```

https://github.com/shinya7y/weights/releases/download/v1.0.2/res2net50_v1b_26w_4s-3cf99910_mmdetv2-92ed3313.pth
was converted with `map_location='cpu'`.
