### ISSUE TITLE
Hardware requirements for trainning Waymo Open Dataset

### ISSUE THREAD

**Issue by anhhna** [shinya7y/UniverseNet#25]
![image](https://user-images.githubusercontent.com/8412288/127086337-f8553d59-af79-4592-8147-cc6a13270d9a.png)

In the README said that "A machine with 208-416 GB of CPU memory is needed for full training as of MMDetection v2.0.", CPU memory that you means in this situation is RAM?, so what's the requirements of GPU, CPU, RAM, Hard disk for training this dataset, thank you so much for answering this quetion!

**Comment by shinya7y** [comment]
CPU memory means RAM. The RAM usage could be reduced by changing code and annotation format.

* GPU
  GPU memory usage is written in "Mem (GB)" in the README.
  I mainly use 4 Tesla T4 (~15GB) and used 8 V100 (~16GB) in the competition.
  GPUs with more memory (e.g., 24GB, 32GB) are preferred to increase batch size or try transformers.
* CPU
  Less requirement. It may be better if the number of cores is twice the number of GPUs for `workers_per_gpu=2`.
* Hard disk
  2TB will be preferred to smoothly download the dataset and convert it for 2D detection.

**Comment by anhhna** [comment]
wow, it's a super computer, can I train Waymo Dataset on my Computer, Core i7, Ram 64gb, RTX 3070 8gb, 2Tb Harddisk, I think not, is it right?

**Comment by shinya7y** [comment]
You can try `f0train` (1/10 size dataset), which requires less RAM. However, training on one RTX 3070 will take a very long time. I recommend smaller datasets.

**Comment by anhhna** [comment]
ok thank you so much, I will try it, I closed the issue
