### ISSUE TITLE
Test picture

### ISSUE THREAD

**Issue by sure7018** [shinya7y/UniverseNet#28]
Hello, when I test with pictures, I find that only the bounding box and accuracy are displayed in the test results, and the test category is not displayed. What should I do?

![image](https://user-images.githubusercontent.com/83046747/137240860-01192241-a3c8-4d01-a804-c6a18b684983.png)

**Comment by shinya7y** [comment]
`▯▯` looks tofu. https://english.stackexchange.com/questions/296505/where-is-tofu-for-font-fallback-box-glyph-coming-from
Is the category written in Chinese?

**Comment by sure7018** [comment]
> `▯▯` looks tofu. https://english.stackexchange.com/questions/296505/where-is-tofu-for-font-fallback-box-glyph-coming-from Is the category written in Chinese?

Yes, this is a data set of the competition. It is marked in Chinese. This Chinese marking is really troublesome.

**Comment by shinya7y** [comment]
The tofu may disappear by changing the font setting of matplotlib, but it will be easier to replace categories with English.

**Comment by sure7018** [comment]
OK, I'll try. Thank you
