### ISSUE TITLE
UniverseNet Pretrained on Manga109

### ISSUE THREAD

**Issue by JosephAssaker** [shinya7y/UniverseNet#29]
Hello there,

I can't seem to find any checkpoints for the UniverseNet other than checkpoints from COCO pretraining. Are there any checkpoints available that have been pretrained on the Manga109 dataset?

**Comment by shinya7y** [comment]
Manga109 checkpoints are here.
https://github.com/shinya7y/UniverseNet/blob/master/configs/manga109/README.md#results

**Comment by JosephAssaker** [comment]
Thank you for your help, however when I use the following:

```
config_file = 'configs/manga109/universenet50_2008_fp16_4x4_mstrain_480_960_1x_manga109s.py'
checkpoint_file = 'universenet50_2008_fp16_4x4_mstrain_480_960_1x_manga109s_20201220_epoch_12-6af914a4.pth'
```

When I do inferences I am getting classes such as "plotted_plant", "zebra", etc. Rather than getting classes from the manga109 classes (person, face, text). Am I missing something?
