### ISSUE TITLE
Pre-trained checkpoints on Waymo Open Dataset

### ISSUE THREAD

**Issue by KaiChen1998** [shinya7y/UniverseNet#32]
Hi!

Thank you for doing such a wonderful work!

I saw you also did experiments on 2D object detection of Waymo Open Dataset. Do you plan to release the pre-trained detector weights? Sorry but I think I can not found the checkpoints in this repo?

Thank you!

**Comment by shinya7y** [comment]
Hi! Please follow this [Notes](https://github.com/shinya7y/UniverseNet/tree/master/configs/waymo_open#notes).
