### ISSUE TITLE
  f'{obj_type} is not in the {registry.name} registry') KeyError: 'WaymoOpenDataset is not in the dataset registry'   and python -m torch.distributed.launch --nproc_per_node=$GPUS --master_port=$PORT \     SyntaxError: invalid syntax  

### ISSUE THREAD

**Issue by gopikrishnabs** [shinya7y/UniverseNet#34]
Hello @shinya7y 

1st error = f'{obj_type} is not in the {registry.name} registry') KeyError: 'WaymoOpenDataset is not in the dataset registry' 

Executed statement:      
! python /content/drive/Shareddrives/som1/Universenet/UniverseNet/tools/train.py  /content/drive/Shareddrives/som1/Universenet/UniverseNet/configs/waymo_open/retinanet_r50_fpn_fp16_4x4_1x_waymo_open_f0.py

2nd error =  python -m torch.distributed.launch --nproc_per_node=$GPUS --master_port=$PORT \     SyntaxError: invalid syntax  

Executed statement
  ! bash python /content/drive/Shareddrives/som1/Universenet/UniverseNet/tools/dist_train.sh

I am working on 2d detection on the waymo open dataset I am getting the 1st error when I execute the train.py  file in tools folder and 2nd error is when dist_train.sh is executed.

For the first error I am working in google colab environement I am not unable to modify the files installed.
Is there any way I can solve this issue I have seen this issue and I also know that the waymo open dataset is declared in **mmdet** in the "UniverseNet" folder but when I am executing the system is verifying from the installed library in "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py" 

Am I executing the scripts properly?

for the second one I don't have much idea about pytorch so I am not sure what should be passed to port values, etc....

*dist_train.sh* file while executing

CONFIG='/content/drive/Shareddrives/som1/Universenet/UniverseNet/configs/waymo_open/retinanet_r50_fpn_fp16_4x4_1x_waymo_open_f0.py'
GPUS= 1
PORT=1000

PYTHONPATH="/content/drive/Shareddrives/som1/Universenet/UniverseNet/mmdet/" 

python -m torch.distributed.launch --nproc_per_node=$GPUS --master_port=$PORT \
    $(dirname "$0")/train.py $CONFIG --launcher pytorch ${@:3}

I have less practical experience in ML so any help would be appretiated.
Thank you

**Comment by shinya7y** [comment]
I think 1st error is caused by a failed installation.
I recommend playing with the [MMDetection repository](https://github.com/open-mmlab/mmdetection) first.
The [colab tutorial in this repo](https://github.com/shinya7y/UniverseNet/blob/master/demo/MMDet_Tutorial.ipynb) is older than [that in the MMDet repo](https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_Tutorial.ipynb).
If you can run the colab tutorial without errors, please change `!git clone` to use the waymo open dataset.

2nd error: A possible fix is `GPUS= 1` -> `GPUS=1`.
I can't help much with errors due to a specific shell script.

**Comment by shinya7y** [comment]
For the 2nd error, `dist_train.sh` should be executed by bash (or compatible shell), not python.

**Comment by gopikrishnabs** [comment]
Thanks for replying 

For the first error, I tried this tutorial [https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_Tutorial.ipynb](url) everything is working fine I was able to download pre-trained weights and do inference. 
![image](https://user-images.githubusercontent.com/53032421/167770391-250abead-50ed-4000-a790-39a04141de55.png)

But if I try to run the same on waymo dataset the error is as below
![image](https://user-images.githubusercontent.com/53032421/167770339-e670ada1-52ad-4394-a981-5a967f444e1b.png)

I understood the error but I don't know in which file I have to register the waymo open dataset 

I also tried running this command so that waymo open dataset will be recognized but still the same error 
!python /content/drive/Shareddrives/som1/Universenet/UniverseNet/mmdet/datasets/waymo_open.py

I also tried removing the python for running shell file it also leads to the same error as first. 
This is the file I am not sure that I have added the proper value to PYTHONPATH
![image](https://user-images.githubusercontent.com/53032421/167774507-928a4aa0-7ec5-4d98-a811-088af5be9820.png)


I have already converted the waymo to coco format using Waymo_to_coco file 

Pic of waymo detection file
![image](https://user-images.githubusercontent.com/53032421/167773400-37c66049-a290-4bf8-8dc4-c4075412c3fe.png)

**Comment by shinya7y** [comment]
Installing MMDetection will cause the error.

```bash
!git clone https://github.com/open-mmlab/mmdetection.git
%cd mmdetection

!pip install -e .
```

To register `WaymoOpenDataset`, you need to install UniverseNet repo as `mmdet`.

```bash
!git clone https://github.com/shinya7y/UniverseNet.git
%cd UniverseNet

!pip install -e .
```

**Comment by gopikrishnabs** [comment]
Thanks, I was able to execute the script. I would like to know how did you train the model (final model with full waymo open dataset) because it requires a lot of memory was it a cloud-based machine? I tried using cloud resources but none are providing a single machine. I finally came across Jarvis cloud service which I think was good. Any suggestions?

**Comment by shinya7y** [comment]
I have written hardware requirements in https://github.com/shinya7y/UniverseNet/issues/25 .
I use GCP only and don't know which cloud service is the best.

**Comment by gopikrishnabs** [comment]
Nice, I also tried taking GCP instance but due to high demand there are no GPU's available did you contact any sales team or something like that. I am using Colab pro which is not suitable so I am thinking of purchasing a cloud instance any info regarding that would be helpful as I looked into all the cloud providers for gpu instances. 

For the Waymo data set did you apply any more pre-processing methods for the final model or its the same one in the repo.  And if there are any pre-processing techniques that you applied I would like to know about those so that I can play with them.

**Comment by shinya7y** [comment]
In my experience, GCP quota requests were approved in 2019, but rejected in 2020.

Pre-processing is not special as the configs in this repo. Data augmentation and TTA are worth tuning.

**Comment by gopikrishnabs** [comment]
Okay, thanks for your responses. I will close this issue.

**Comment by gopikrishnabs** [comment]
Hello, Is there a way to save the weights of the model of Universenet  currently the automatic saving is not happening in the work directory.

**Comment by shinya7y** [comment]
Many issues are due to incorrect usage of mmdetection. Please read mmdet documents and make sure your settings are correct.

If the problem persists after thorough investigation, please open another issue using the issue template of `Error report`.
