### ISSUE TITLE
How to save the predicted bbox in a file?

### ISSUE THREAD

**Issue by nile649** [shinya7y/UniverseNet#37]
Question : How to save the predicted bbox in a file?

**Comment by shinya7y** [comment]
Please see this document.
https://github.com/shinya7y/UniverseNet/blob/master/docs/en/1_exist_data_model.md

```
--out results.pkl
```

```
--format-only \
--options "jsonfile_prefix=./mask_rcnn_test-dev_results"
```

- `jsonfile_prefix` for most datasets
- `outfile_prefix` for WOD
