### ISSUE TITLE
AssertionError: Default process group is not initialized

### ISSUE THREAD

**Issue by iampartho** [shinya7y/UniverseNet#8]
I got this error while trying to train [this](https://github.com/shinya7y/UniverseNet/blob/master/configs/universenet/universenet50_2008_fp16_4x4_mstrain_480_960_2x_coco.py) model, I have also trained [this](https://github.com/shinya7y/UniverseNet/blob/master/configs/universenet/universenet50_gfl_fp16_4x4_mstrain_480_960_2x_coco.py) and [this](https://github.com/shinya7y/UniverseNet/blob/master/configs/universenet/universenet101_gfl_fp16_4x4_mstrain_480_960_2x_coco.py) model before without this or any errors. Anyone could help me debug it. I am using google colab by modifying [this](https://github.com/shinya7y/UniverseNet/blob/master/demo/MMDet_Tutorial.ipynb) notebook. Thanks.

**Comment by shinya7y** [comment]
The cause may be SyncBN used in [this file](https://github.com/shinya7y/UniverseNet/blob/master/configs/_base_/models/universenet50_2008.py).

> SyncBN only works with distributed environment, you may either use `tools/dist_test.sh` or modify SyncBN to BN manually during testing.
https://github.com/open-mmlab/mmdetection/issues/847#issuecomment-504421173

**Comment by iampartho** [comment]
Thanks for the clarifications, I could start the training without the error by changing it from "SyncBN" to "BN". Closing the issue.
