### ISSUE TITLE
Request for NightOwls Model weights

### ISSUE THREAD

**Issue by shardulparab97** [shinya7y/UniverseNet#9]
Came across your repository and it is really helpful and intuitive.

With recent major focus on night time object detection, would it be possible for you to share your NightOwls model weights?

It would mean a great deal to further research efforts.
Thanks! :)

**Comment by shinya7y** [comment]
Please follow this [Notes](https://github.com/shinya7y/UniverseNet/tree/master/configs/waymo_open#notes), because the NightOwls model was pre-trained on Waymo Open.

**Comment by shardulparab97** [comment]
Sure would do the same. Thank you.

**Comment by shardulparab97** [comment]
@shinya7y  please check the message sent to your LinkedIn account.
